/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 white-windbreaker.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/white-windbreaker.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Retopo_polySurface2_hanger_hanger008.geometry} material={materials['Material #647.002']} position={[-4.35, 1.94, 15]} scale={0.01} />
      <mesh geometry={nodes.polySurface10.geometry} material={materials['windbreaker-BK']} position={[-4.33, 1.54, 15]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/white-windbreaker.glb')
